name: telegram_nav_bar
description: >-
  A highly customizable Flutter package that replicates the latest
  Telegram-style bottom navigation bar with smooth glassmorphic blur
  effects, animated indicator bubbles, and seamless dark/light mode support.
version: 0.0.1
repository: https://github.com/jaberio/telegram-nav-bar
issue_tracker: https://github.com/jaberio/telegram-nav-bar/issues

topics:
  - navigation
  - bottom-navigation
  - ui
  - animation
  - glassmorphism

screenshots:
  - description: 'Telegram Nav Bar Example 1'
    path: doc/Screenshot_1772317073.png
  - description: 'Telegram Nav Bar Example 2'
    path: doc/Screenshot_1772317082.png

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
